In [12]:
import numpy as np

n = np.array([1, 2, 3, 4])

print(n)
print(type(n))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
n2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


print(n2)
print(type(n2))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [10]:
n3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])

print(n3)
print(type(n3))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
<class 'numpy.ndarray'>


In [16]:
print(n.ndim, n2.ndim, n3.ndim)
print(n.shape, n2.shape, n3.shape)
print(n.size, n2.size, n3.size)

1 2 3
(4,) (2, 4) (1, 3, 4)
4 8 12
