In [2]:
import numpy as np

n = np.array([1, 2, 3, 4])

print(n)
print(type(n))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
n2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])


print(n2)
print(type(n2))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [4]:
n3 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])

print(n3)
print(type(n3))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
<class 'numpy.ndarray'>


In [5]:
print(n.ndim, n2.ndim, n3.ndim)
print(n.shape, n2.shape, n3.shape)
print(n.size, n2.size, n3.size)

1 2 3
(4,) (2, 4) (1, 3, 4)
4 8 12


In [18]:
z = np.zeros((2, 4))
print(z)

x = np.ones([2, 5], dtype=str)
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [19]:
y = np.eye(5)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [68]:
k = np.random.random((2,3))
print(k)

m = np.random.randint(-100, 100, (2,3))
m

[[0.15009147 0.90130407 0.06701976]
 [0.23745283 0.00849595 0.2573061 ]]


array([[ 75, -10,  44],
       [  6,  -5, -65]], dtype=int32)

In [79]:
a = np.array([1,2,3])
b = np.array([1,2,3])

c = a+b
d = a*b
e = a/b 
f = a-b

print(c, d, e, f, sep="\n")


[2 4 6]
[1 4 9]
[1. 1. 1.]
[0 0 0]


In [84]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(a.mean())

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
2.0


In [97]:
s = np.array([[2, 4], [5, 11], [3, 4]])
print(s.mean())
print(s.mean(axis=0))
print(s.mean(axis=1))

4.833333333333333
[3.33333333 6.33333333]
[3.  8.  3.5]


In [98]:
print(s.sum())
print(s.sum(axis=0))
print(s.sum(axis=1))

29
[10 19]
[ 6 16  7]


In [99]:
print(s.max())
print(s.max(axis=0))
print(s.max(axis=1))

11
[ 5 11]
[ 4 11  4]


In [100]:
print(s.min())
print(s.min(axis=0))
print(s.min(axis=1))

2
[2 4]
[2 5 3]


In [101]:
print(s.shape)

(3, 2)
